import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar.jsx";
import Footer from "@/components/Footer.jsx";
import SaleHeader from "@/components/SaleHeader.jsx";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased min-h-screen flex flex-col`}>
        <div className="hidden md:block h-12">
          <SaleHeader/>
        </div>
        <div className="md:h-20 h-14">
          <Navbar/>
        </div>
        <main className="flex-grow">
          {children}
        </main>
        <div className="w-full">
          <Footer />
        </div>
      </body>
    </html>
  );
}
