export const env = {
    API_URL: process.env.NEXT_PUBLIC_API_URL || 'http://localhost:8080',
    FIREBASE_API_KEY: process.env.NEXT_PUBLIC_FIREBASE_API_KEY,
    FIREBASE_AUTH_DOMAIN: process.env.NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN,
    FIREBASE_PROJECT_ID: process.env.NEXT_PUBLIC_FIREBASE_PROJECT_ID,
    FIREBASE_STORAGE_BUCKET : process.env.NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET,
    FIREBASE_MESSAGING_ID:process.env.NEXT_PUBLIC_FIREBASE_MESSAGING_ID,
    FIREBASE_APP_ID:process.env.NEXT_PUBLIC_FIREBASE_APP_ID,
    FIREBASE_MEASUREMENT_ID:process.env.NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID,
    CLOUDINARY_NAME:process.env.NEXT_PUBLIC_CLOUDINARY_NAME,
    CLOUDINARY_API:process.env.NEXT_PUBLIC_CLOUDINARY_API,
    CLOUDINARY_API_SECRET:process.env.NEXT_PUBLIC_CLOUDINARY_API_SECRET
  }
  